-- コマンドパレット: Neovim 標準操作のうち覚えにくいが頻繁に使うもの
-- desc は 2 行構成:  1 行目=動作の説明、2 行目=原理 / 補足

return {
	{
		group = "Search",
		name = "Clear search highlight",
		desc = "検索ハイライトをクリア\n:nohlsearch",
		category = "Builtin",
		kind = "cmd",
		action = "nohlsearch",
	},
	{
		group = "Window",
		name = "Split window vertically",
		desc = "ウィンドウを縦分割 (右に新規)\n:vsplit",
		category = "Builtin",
		kind = "cmd",
		action = "vsplit",
	},
	{
		group = "Window",
		name = "Split window horizontally",
		desc = "ウィンドウを横分割 (下に新規)\n:split",
		category = "Builtin",
		kind = "cmd",
		action = "split",
	},
	{
		group = "Window",
		name = "Close current window",
		desc = "ウィンドウを閉じる (現在のウィンドウのみ)\n:close",
		category = "Builtin",
		kind = "cmd",
		action = "close",
	},
	{
		group = "Window",
		name = "Equalize window sizes",
		desc = "ウィンドウサイズを均等に揃える\n<C-w>= : <C-w>=window prefix + '='=等しく",
		category = "Builtin",
		kind = "keys",
		action = "<C-w>=",
	},
	{
		group = "Window",
		name = "Maximize window height",
		desc = "現ウィンドウの高さを最大化 (他は最小化、<C-w>= で戻る)\n<C-w>_ : <C-w>=window prefix + _=下線(横に広がる象形)",
		category = "Builtin",
		kind = "keys",
		action = "<C-w>_",
	},
	{
		group = "Window",
		name = "Maximize window width",
		desc = "現ウィンドウの幅を最大化 (他は最小化、<C-w>= で戻る)\n<C-w>| : <C-w>=window prefix + |=縦棒(縦に広がる象形)",
		category = "Builtin",
		kind = "keys",
		action = "<C-w><Bar>",
		keys = "<C-w>|", -- 表示用 (action は <Bar> エスケープが必要、表示はリテラルが見やすい)
	},
	{
		group = "Window",
		name = "Rotate windows",
		desc = "現ウィンドウを隣と入れ替え (順方向)。<C-w>R で逆回転\n<C-w>r : <C-w>=window prefix + r=rotate",
		category = "Builtin",
		kind = "keys",
		action = "<C-w>r",
	},
	{
		group = "Buffer",
		name = "Save all buffers",
		desc = "全バッファを保存\n:wall",
		category = "Builtin",
		kind = "cmd",
		action = "wall",
	},
	{
		group = "Edit",
		name = "Retab buffer",
		desc = "タブをスペースに変換 (現バッファ)\n:retab",
		category = "Builtin",
		kind = "cmd",
		action = "retab",
	},
	{
		group = "Edit",
		name = "Trim trailing whitespace",
		desc = "行末の空白を削除 (全行 trim)\n:%s/\\s\\+$//e",
		category = "Builtin",
		kind = "fn",
		action = function()
			vim.cmd([[%s/\s\+$//e]])
		end,
	},
	{
		group = "Mark",
		name = "List marks",
		desc = "マーク一覧\n:marks",
		category = "Builtin",
		kind = "cmd",
		action = "marks",
	},
	{
		group = "Mark",
		name = "Set local mark to a",
		desc = "現在位置をマーク a として記録 (a は a-z 任意、buffer ローカル)\nma : m=mark + a=識別子",
		category = "Builtin",
		kind = "keys",
		action = "ma",
	},
	{
		group = "Mark",
		name = "Set global mark to A",
		desc = "現在位置をグローバルマーク A として記録 (A は A-Z 任意、全 buffer 横断)\nmA : m=mark + A=大文字識別子",
		category = "Builtin",
		kind = "keys",
		action = "mA",
	},
	{
		group = "Mark",
		name = "Jump to mark a (line + col)",
		desc = "マーク a の位置に行 + 列まで完全に復元ジャンプ (a は a-z / A-Z 任意)\n`a : `(backtick)=正確位置ジャンプ + a=マーク識別子",
		category = "Builtin",
		kind = "keys",
		action = "`a",
	},
	{
		group = "Mark",
		name = "Jump to mark a (line head)",
		desc = "マーク a の行頭にジャンプ (行は復元、列は捨てる。a は a-z / A-Z 任意)\n'a : '(apostrophe)=行頭ジャンプ + a=マーク識別子",
		category = "Builtin",
		kind = "keys",
		action = "'a",
	},
	{
		group = "Mark",
		name = "Delete all marks",
		desc = "全マークを削除\n:delmarks!",
		category = "Builtin",
		kind = "cmd",
		action = "delmarks!",
	},
	{
		group = "Register",
		name = "List registers",
		desc = "レジスタ一覧\n:registers",
		category = "Builtin",
		kind = "cmd",
		action = "registers",
	},
	{
		group = "Jump",
		name = "Jump back (cursor history)",
		desc = "ジャンプリストを 1 つ古い位置に戻る (ジャンプ系の移動を遡る)\n<C-o> : o=Older",
		category = "Builtin",
		kind = "keys",
		action = "<C-o>",
	},
	{
		group = "Jump",
		name = "Jump forward (cursor history)",
		desc = "ジャンプリストを 1 つ新しい位置に進む (<C-o> の逆)\n<C-i> : i=新方向 (実体は Tab と同じキー)",
		category = "Builtin",
		kind = "keys",
		action = "<C-i>",
	},
	{
		group = "Jump",
		name = "Jump to previous change",
		desc = "1 つ前の編集位置に戻る (変更リスト)\ng; : g=拡張 prefix + ;=changelist 前",
		category = "Builtin",
		kind = "keys",
		action = "g;",
	},
	{
		group = "Jump",
		name = "Jump to next change",
		desc = "1 つ後の編集位置に進む (g; の逆方向)\ng, : g=拡張 prefix + ,=changelist 後",
		category = "Builtin",
		kind = "keys",
		action = "g,",
	},
	{
		group = "Jump",
		name = "List jumps",
		desc = "ジャンプリスト\n:jumps",
		category = "Builtin",
		kind = "cmd",
		action = "jumps",
	},
	{
		group = "Jump",
		name = "List changes",
		desc = "直前の変更一覧\n:changes",
		category = "Builtin",
		kind = "cmd",
		action = "changes",
	},
	{
		group = "Fold",
		name = "Open all folds",
		desc = "すべての fold を再帰的に開く (zo は 1 階層のみ)\nzR : z=fold prefix + R=Reduce (大文字は再帰/全体)",
		category = "Builtin",
		kind = "keys",
		action = "zR",
	},
	{
		group = "Fold",
		name = "Close all folds",
		desc = "すべての fold を再帰的に閉じる (zc は 1 階層のみ)\nzM : z=fold prefix + M=More (大文字は再帰/全体)",
		category = "Builtin",
		kind = "keys",
		action = "zM",
	},
	{
		group = "Clipboard",
		name = "Copy buffer file path",
		desc = "バッファのファイル名 (絶対パス) をクリップボードへコピー\nfn: vim.fn.setreg('+', vim.fn.expand('%:p'))",
		category = "Builtin",
		kind = "fn",
		action = function()
			local path = vim.fn.expand("%:p")
			vim.fn.setreg("+", path)
			vim.notify("Copied: " .. path)
		end,
	},

	-- ─── テキストオブジェクト (operator + i/a + object) ───
	{
		group = "TextObject",
		name = "Change inner word",
		desc = "単語の中身を削除して挿入モードに入る\nciw : c=change + i=inner + w=word",
		category = "Builtin",
		kind = "keys",
		action = "ciw",
	},
	{
		group = "TextObject",
		name = "Change inner quote (\")",
		desc = "\" ... \" の中身だけ書き換え\nci\" : c=change + i=inner + \"=double quote",
		category = "Builtin",
		kind = "keys",
		action = "ci\"",
	},
	{
		group = "TextObject",
		name = "Delete around braces",
		desc = "{ ... } を中括弧ごと削除 (around は外側まで含む)\nda{ : d=delete + a=around + {=braces",
		category = "Builtin",
		kind = "keys",
		action = "da{",
	},
	{
		group = "TextObject",
		name = "Yank inner parens",
		desc = "( ... ) の中身だけヤンク (括弧は含まない)\nyi( : y=yank + i=inner + (=parens",
		category = "Builtin",
		kind = "keys",
		action = "yi(",
	},
	{
		group = "TextObject",
		name = "Select inner paragraph",
		desc = "空行で区切られた段落の中身を選択\nvip : v=visual + i=inner + p=paragraph",
		category = "Builtin",
		kind = "keys",
		action = "vip",
	},
	{
		group = "TextObject",
		name = "Change inner tag",
		desc = "<a>...</a> の中身だけ書き換え (HTML/JSX 等)\ncit : c=change + i=inner + t=tag",
		category = "Builtin",
		kind = "keys",
		action = "cit",
	},
	{
		group = "TextObject",
		name = "Change inner WORD",
		desc = "foo-bar.baz のような記号混じりの塊ごと書き換え (w は記号で区切られるが W は空白だけが境界)\nciW : c=change + i=inner + W=WORD",
		category = "Builtin",
		kind = "keys",
		action = "ciW",
	},
	{
		group = "TextObject",
		name = "Change around word",
		desc = "単語 + 後続の空白も削除して挿入 (i との違い: 周囲の境界まで含む)\ncaw : c=change + a=around + w=word",
		category = "Builtin",
		kind = "keys",
		action = "caw",
	},
	{
		group = "TextObject",
		name = "Change around quote (\")",
		desc = "\"…\" をクォート記号ごと削除して挿入 (i との違い: 区切りまで含む)\nca\" : c=change + a=around + \"=double quote",
		category = "Builtin",
		kind = "keys",
		action = "ca\"",
	},
	{
		group = "TextObject",
		name = "Delete around parens",
		desc = "( … ) を括弧記号ごと削除 (中身 + 開閉括弧)\nda( : d=delete + a=around + (=parens",
		category = "Builtin",
		kind = "keys",
		action = "da(",
	},
	{
		group = "TextObject",
		name = "Change inner sentence",
		desc = "'.', '!', '?' で区切られる「文」の中身だけ書き換え\ncis : c=change + i=inner + s=sentence",
		category = "Builtin",
		kind = "keys",
		action = "cis",
	},
	{
		group = "TextObject",
		name = "Change inner paragraph",
		desc = "空行で区切られた「段落」の中身を丸ごと書き換え\ncip : c=change + i=inner + p=paragraph",
		category = "Builtin",
		kind = "keys",
		action = "cip",
	},

	-- ─── 編集 (繰り返し / 数値 / ブラックホール) ───
	{
		group = "Edit",
		name = "Repeat last change",
		desc = "直前の編集操作 (insert モード入り → 変更 → Esc) を 1 まとまりとして繰り返す\n. (ドット)",
		category = "Builtin",
		kind = "keys",
		action = ".",
	},
	{
		group = "Edit",
		name = "Increment number under cursor",
		desc = "カーソル下の数値を +1。前置数で個数指定 (例: 5<C-a> で +5)\n<C-a>",
		category = "Builtin",
		kind = "keys",
		action = "<C-a>",
	},
	{
		group = "Edit",
		name = "Decrement number under cursor",
		desc = "カーソル下の数値を -1。前置数で個数指定 (例: 5<C-x> で -5)\n<C-x>",
		category = "Builtin",
		kind = "keys",
		action = "<C-x>",
	},
	{
		group = "Edit",
		name = "Sequential numbers (visual)",
		desc = "Visual 選択した複数行を行ごとに +1, +2, +3... と連番化\ng<C-a> : g=global modifier + <C-a>=increment",
		category = "Builtin",
		kind = "keys",
		action = "g<C-a>",
	},
	{
		group = "Edit",
		name = "Delete line to black hole",
		desc = "デフォルトレジスタを汚さず行削除 (直前ヤンクが保持される)\n\"_dd : \"_=ブラックホールレジスタ + dd=行削除",
		category = "Builtin",
		kind = "keys",
		action = '"_dd',
	},

	-- ─── マクロ (q = record toggle、@ = replay) ───
	{
		group = "Macro",
		name = "Record macro to register a",
		desc = "操作を記録開始。再度 q で停止 (a-z で別レジスタ可)\nqa : q=record toggle + a=レジスタ名",
		category = "Builtin",
		kind = "keys",
		action = "qa",
	},
	{
		group = "Macro",
		name = "Replay macro from register a",
		desc = "レジスタ a に保存したマクロを実行 (前置数で反復: 5@a)\n@a : @=play register + a=レジスタ名",
		category = "Builtin",
		kind = "keys",
		action = "@a",
	},
	{
		group = "Macro",
		name = "Replay last macro",
		desc = "直前に @x で実行したマクロを再実行\n@@ : @ + @ = 直前の play register を繰り返し",
		category = "Builtin",
		kind = "keys",
		action = "@@",
	},

	-- ─── 履歴ウィンドウ (q + : / q + /) ───
	{
		group = "History",
		name = "Open command-line history window",
		desc = "コマンド履歴を編集可能バッファで開く (Enter で実行)\nq: : q=record-like prefix + :=cmdline",
		category = "Builtin",
		kind = "keys",
		action = "q:",
	},
	{
		group = "History",
		name = "Open search history window",
		desc = "検索履歴を編集可能バッファで開く\nq/ : q=record-like prefix + /=search",
		category = "Builtin",
		kind = "keys",
		action = "q/",
	},

	-- ─── 大文字小文字変換 (gU=upper / gu=lower / g~=toggle はオペレータ) ───
	{
		group = "Case",
		name = "Uppercase word",
		desc = "単語を大文字化\ngUw : gU=uppercase オペレータ + w=word モーション",
		category = "Builtin",
		kind = "keys",
		action = "gUw",
	},
	{
		group = "Case",
		name = "Lowercase word",
		desc = "単語を小文字化\nguw : gu=lowercase オペレータ + w=word モーション",
		category = "Builtin",
		kind = "keys",
		action = "guw",
	},
	{
		group = "Case",
		name = "Toggle case word",
		desc = "単語の大文字/小文字を反転\ng~w : g~=case-toggle オペレータ + w=word",
		category = "Builtin",
		kind = "keys",
		action = "g~w",
	},
	{
		group = "Case",
		name = "Uppercase line",
		desc = "現在行を大文字化\ngUU : gU を 2 回でオペレータ対象が「現在行」になる (vim のオペレータ二重押し = 行ルール)",
		category = "Builtin",
		kind = "keys",
		action = "gUU",
	},

	-- ─── ビュー (スクロール位置調整: z + 位置文字) ───
	{
		group = "View",
		name = "Center cursor line in window",
		desc = "カーソル行を画面中央に (位置はそのまま、表示だけ動く)\nzz : z=view prefix + z=center",
		category = "Builtin",
		kind = "keys",
		action = "zz",
	},
	{
		group = "View",
		name = "Scroll cursor line to top",
		desc = "カーソル行を画面上端に\nzt : z=view prefix + t=top",
		category = "Builtin",
		kind = "keys",
		action = "zt",
	},
	{
		group = "View",
		name = "Scroll cursor line to bottom",
		desc = "カーソル行を画面下端に\nzb : z=view prefix + b=bottom",
		category = "Builtin",
		kind = "keys",
		action = "zb",
	},

	-- ─── Quickfix (c で始まる ex コマンド群) ───
	{
		group = "Quickfix",
		name = "Open quickfix window",
		desc = "クイックフィックスウィンドウを開く\n:copen (c=quickfix + open=開く)",
		category = "Builtin",
		kind = "cmd",
		action = "copen",
	},
	{
		group = "Quickfix",
		name = "Close quickfix window",
		desc = "クイックフィックスウィンドウを閉じる\n:cclose",
		category = "Builtin",
		kind = "cmd",
		action = "cclose",
	},
	{
		group = "Quickfix",
		name = "Next quickfix entry",
		desc = "次のエントリへジャンプ\n:cnext (短縮 :cn)",
		category = "Builtin",
		kind = "cmd",
		action = "cnext",
	},
	{
		group = "Quickfix",
		name = "Previous quickfix entry",
		desc = "前のエントリへジャンプ\n:cprev (短縮 :cp)",
		category = "Builtin",
		kind = "cmd",
		action = "cprev",
	},
	{
		group = "Quickfix",
		name = "Vimgrep (prefill cmdline)",
		desc = "grep → quickfix。コマンドラインに雛形を出した状態で開くので // にパターン入力\n:vimgrep // **/*",
		category = "Builtin",
		kind = "fn",
		action = function()
			vim.api.nvim_feedkeys(":vimgrep // **/*", "n", false)
		end,
	},
	{
		group = "Quickfix",
		name = "Bulk substitute (cdo, prefill)",
		desc = "全 quickfix エントリに一括置換 + 保存。雛形入力で待つ\n:cdo s/old/new/g | update",
		category = "Builtin",
		kind = "fn",
		action = function()
			vim.api.nvim_feedkeys(":cdo s/old/new/g | update", "n", false)
		end,
	},

	-- ─── 検索 / ジャンプ / Visual / Undo ───
	{
		group = "Search",
		name = "Search word under cursor",
		desc = "カーソル下の単語を完全一致 \\<word\\> で前方検索。# で逆方向、n/N で次/前へ\n*",
		category = "Builtin",
		kind = "keys",
		action = "*",
	},
	{
		group = "Jump",
		name = "Jump to matching bracket",
		desc = "カーソル下の () [] {} に対応するもう片方に瞬間ジャンプ (matchpairs 設定に従う)\n%",
		category = "Builtin",
		kind = "keys",
		action = "%",
	},
	{
		group = "Visual",
		name = "Reselect last visual",
		desc = "直前の Visual 選択範囲を再選択 (>gv> でインデント連打等)\ngv : g=直前を示す接頭 + v=visual",
		category = "Builtin",
		kind = "keys",
		action = "gv",
	},
	{
		group = "Undo",
		name = "Time-travel undo (prefill)",
		desc = "時間ベース undo で過去状態にロールバック。:later で進む。単位: s/m/h/d/f(ファイル変更単位)\n:earlier 5m (= 5 分前)",
		category = "Builtin",
		kind = "fn",
		action = function()
			vim.api.nvim_feedkeys(":earlier ", "n", false)
		end,
	},
}
