-- コマンドパレット: 自分で定義済みのキーマップへの導線
-- desc は 2 行構成: 1 行目=動作の説明、2 行目=呼び出すコマンド or 補足

return {
	{
		group = "Find",
		name = "Find files by name",
		desc = "ファイル名で検索 (カレントディレクトリ以下)\n:Telescope find_files",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope find_files",
		keys = "<leader>ff",
	},
	{
		group = "Find",
		name = "Live grep",
		desc = "grep 検索 (カレントディレクトリ以下)\n:Telescope live_grep",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope live_grep",
		keys = "<leader>fg",
	},
	{
		group = "Find",
		name = "Fuzzy find in current buffer",
		desc = "現在のバッファ内をファジー検索\n:Telescope current_buffer_fuzzy_find",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope current_buffer_fuzzy_find",
		keys = "<leader>fn",
	},
	{
		group = "Buffer",
		name = "List open buffers",
		desc = "開いているバッファ一覧\n:Telescope buffers",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope buffers",
		keys = "<leader>fb",
	},
	{
		group = "Find",
		name = "Search help docs",
		desc = "ヘルプドキュメント検索\n:Telescope help_tags",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope help_tags",
		keys = "<leader>fh",
	},
	{
		group = "Find",
		name = "List all keymaps (raw)",
		desc = "Neovim 全マップを Telescope で閲覧 (curated パレットではなく raw 一覧)\n:Telescope keymaps",
		category = "Keymap",
		kind = "cmd",
		action = "Telescope keymaps",
	},
	{
		group = "File",
		name = "Toggle file tree",
		desc = "ファイルツリー切り替え\n:NvimTreeToggle",
		category = "Keymap",
		kind = "cmd",
		action = "NvimTreeToggle",
		keys = "<leader>e",
	},
	{
		group = "Buffer",
		name = "Close buffer",
		desc = "バッファを閉じる (ウィンドウレイアウト保持)\n<leader>bd → bprevious + bdelete (base.lua の自作)",
		category = "Keymap",
		kind = "keys",
		action = "<leader>bd",
		keys = "<leader>bd",
	},
	{
		group = "View",
		name = "Toggle line wrap",
		desc = "行折り返しトグル (wrap on/off)\n<M-z> → vim.opt.wrap をトグル (base.lua の自作)",
		category = "Keymap",
		kind = "keys",
		action = "<M-z>",
		keys = "<M-z>",
	},
	{
		group = "Clipboard",
		name = "Paste from system clipboard",
		desc = "システムクリップボードから貼り付け\n<leader>v → io.popen('pbpaste') (base.lua の自作)",
		category = "Keymap",
		kind = "keys",
		action = "<leader>v",
		keys = "<leader>v",
	},
}
